import boto3
import math
import time
from operator import itemgetter

# --- Configuration & AWS Clients ---
dynamodb = boto3.resource('dynamodb')
asg_client = boto3.client('autoscaling')
cloudwatch = boto3.client('cloudwatch')

TABLE_NAME = 'ScalingLookupTable'
ASG_NAME = ''
MAX_INS_NUM = 100 # Maximum allowed instances in cluster

# QoS & Queuing Theory Parameters
QOS_PERCENTILE = 0.99  # 'p' in the paper (e.g., TP99)
QOS_TARGET_LATENCY = 40.0  # 't' in the paper (e.g., 40ms)
BOTTLENECK_QPS_PER_INSTANCE = 100.0  # 'u' in the paper

def lambda_handler(event, context):
    """
    Algorithm 2: Hybrid Auto-scaling Implementation
    """
    # 1. Fetch Current Metrics (Mocked for illustration, implement your CW logic)
    cur_ins_num = get_current_instance_count(ASG_NAME)
    cur_qps = get_metric(cloudwatch, 'CurrentQPS')
    cur_slo_latency = get_metric(cloudwatch, 'CurrentTailLatency')
    
    # 2. Fetch Predicted QPS for this minute (From your ML model/DynamoDB)
    predicted_qps = get_predicted_qps()
    
    # 3. Fetch the Performance Model (ins_qps_table) from DynamoDB
    # Format: [{'ins_num': 5, 'qps': 500}, {'ins_num': 6, 'qps': 620}, ...]
    ins_qps_table = get_performance_model(TABLE_NAME)

    # 4. Check for QoS Violation
    if cur_slo_latency > QOS_TARGET_LATENCY:
        print("QoS Violation Detected! Triggering Reactive Scaling.")
        
        # Calculate revised_qps using M/M/s queuing model (Equation 5)
        # Formula: revised_qps = s * u + ln(1 - p) / t
        queuing_adjustment = math.log(1 - QOS_PERCENTILE) / QOS_TARGET_LATENCY
        revised_qps = (cur_ins_num * BOTTLENECK_QPS_PER_INSTANCE) + queuing_adjustment
        
        # Take the maximum of current, predicted, and revised QPS
        target_qps = max(cur_qps, predicted_qps, revised_qps)
        
        # Force at least one additional instance during a violation
        target_ins_num = max(search(target_qps, ins_qps_table), cur_ins_num + 1)
        
        # Scale and apply cooldown (disable scale-in for a while)
        scale2ins_num(target_ins_num, cur_ins_num)
        apply_scale_in_cooldown(ASG_NAME)
        
    else:
        print("QoS is stable. Triggering Proactive Scaling.")
        
        # Only consider current traffic and predicted traffic
        target_qps = max(cur_qps, predicted_qps)
        target_ins_num = search(target_qps, ins_qps_table)
        
        scale2ins_num(target_ins_num, cur_ins_num)

    return {"status": "success", "target_capacity": target_ins_num}


# --- Algorithm 3 Implementations ---

def search(target_qps, ins_qps_table):
    """
    Algorithm 3: search(QPS, ins_qps_table)
    Queries the performance model to find required instances.
    """
    # Ensure table is sorted in ascending order by instance number
    sorted_table = sorted(ins_qps_table, key=itemgetter('ins_num'))
    
    for entry in sorted_table:
        if entry['qps'] >= target_qps:
            return entry['ins_num']
            
    return MAX_INS_NUM

def scale2ins_num(target_num, cur_ins_num):
    """
    Algorithm 3: scale2ins_num(num)
    Executes the scaling action against the ASG.
    """
    if target_num > cur_ins_num:
        print(f"Scaling OUT: {cur_ins_num} -> {target_num}")
        asg_client.update_auto_scaling_group(
            AutoScalingGroupName=ASG_NAME,
            DesiredCapacity=int(target_num)
        )
        # Note: Algorithm 3 calls for sleep(warmup_time) here. 
        # In Lambda, it's better to rely on ASG Health Checks rather than sleeping to avoid timeouts.
        
    elif target_num < cur_ins_num:
        if is_scale_in_allowed():
            print(f"Scaling IN: {cur_ins_num} -> {target_num}")
            asg_client.update_auto_scaling_group(
                AutoScalingGroupName=ASG_NAME,
                DesiredCapacity=int(target_num)
            )
        else:
            print("Scale IN ignored due to recent QoS violation cooldown.")


# --- Helper Functions ---
def get_performance_model(table_name):
    # Retrieve your table generated by the Offline Model
    table = dynamodb.Table(table_name)
    response = table.scan()
    return response.get('Items', [])

def apply_scale_in_cooldown(asg_name):
    # Logic to temporarily disable scale-in (e.g., writing a timestamp to DynamoDB or ElastiCache)
    pass

def is_scale_in_allowed():
    # Logic to check if the cooldown period has expired
    return True

# Dummy functions for metrics (Implement Boto3 CloudWatch calls here)
def get_current_instance_count(asg_name): return 5
def get_metric(client, metric_name): return 450.0
def get_predicted_qps(): return 480.0
